### PR TITLE
Shootnshare agdroid 605

### PR DESCRIPTION
**Pull request by damienomurchu**
**Issue (JIRA):**

Part of [AGDROID-605 ](https://issues.jboss.org/browse/AGDROID-605) - Update AeroGear demos to use notification badges

**Changes:**

- adds notification badge functionality to hello-push app
- updates gradle build files to target Android-O

**How to test: (_currently untested_)**

- open app in Android-O, send notification to device and confirm:
- notification received by device
- push notification received when app in background
- notification badge added when app is in background to app icon to indicate unread notification 

@danielpassos @secondsun

### CODE REVIEW

**Comment by damienomurchu** [comment]
Tested this on my local machine & while I've had some issues getting the shootnshare backend working fully, the addition of notification badge functionality in this OR does seem to work

@danielpassos @secondsun @wojta if you get a chance could you review :)

**Comment by danielpassos** [comment]
|   |   |
|---|---|
|screenshot_20170815-205238|agdroid-605-shoot-and-share|

**Comment by danielpassos** [comment]
Landed at https://github.com/aerogear/aerogear-android-cookbook/commit/e4e1fe9e9c1f818f21a573e242ebd5f4ca04d4de

PS: Don't forgot to rebase before send a PR :wink:

**Comment by damienomurchu** [comment]
@danielpassos doh! didn't realise there had been changes pushed before I generated my PR :)

**Pull request closed without merging**
