### PR TITLE
Move OTP demo from aerogear-otp-android-demo

### PR DESCRIPTION
**Pull request by danielpassos**
See: 

* [AGDROID-383](https://issues.jboss.org/browse/AGDROID-383)
* [AGDROID-299](https://issues.jboss.org/browse/AGDROID-299)

### CODE REVIEW

**Comment by danielpassos** [comment]
@secondsun @abstractj Could you give it a spin?

**Comment by abstractj** [comment]
@danielpassos next week for sure.

**Comment by abstractj** [comment]
@danielpassos probably some lint fu is required here:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lint'.
> Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by danielpassos** [comment]
Added lint ignore

**Comment by abstractj** [comment]
@danielpassos landed https://github.com/aerogear/aerogear-android-cookbook/commit/c1961458857a04d20d0ea938f8992a88e4d76ad9

**Pull request closed without merging**
