### PR TITLE
Agdroid 3

### PR DESCRIPTION
**Pull request by secondsun**
These libraries are updated with the latest Android Marshmallow APIs as well as with AGDroid 3.0.0 libraries

### CODE REVIEW

**Comment by matzew** [comment]
@secondsun should we also update this file ? 

https://github.com/aerogear/aerogear-android-cookbook/blob/master/AeroDoc/build.gradle

**Comment by secondsun** [comment]
@matzew Yup we should.

**Comment by secondsun** [comment]
@matzew AeroDoc is up to date, wdyt?

**Comment by matzew** [comment]
:+1:

On Tue, May 17, 2016 at 5:01 PM, Hoyt Summers Pittman <
notifications@github.com> wrote:

> @matzew <https://github.com/matzew> AeroDoc is up to date, wdyt?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-android-cookbook/pull/57#issuecomment-219745766>
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Pull request merged**
