### PR TITLE
Updating to 2.0.0

### PR DESCRIPTION
**Pull request by secondsun**
This is the cookbook examples using 2.0.0.  We will also tag this release.

Things to test:

That all examples work with the latest libraries staged in nexus 

#link https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-4616/
#link https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-4617/
#link https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-4618/
#link https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-4619/
#link https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-4620/
#link https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-4621/
#link https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-4623/

### CODE REVIEW

**Comment by secondsun** [comment]
@matzew @danielpassos @lholmquist @abstractj @qmx @edewit @danbev and anyone else, care to look?

**Comment by danielpassos** [comment]
I sent auth and authz again because I found a problems on these. Here is a list updated

| Library  | Repository                            |
|:---------|:--------------------------------------|
| Core     | https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-4616/  |
| Security | https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-4617/  |
| Store    | https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-4618/  |
| Pipe     | https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-4619/  |
| Auth     | https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-4629/  |
| Authz    | https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-4630/  |
| Push     | https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-4623/  |

**Comment by danielpassos** [comment]
To test that using nexus links, put that file[1] in your ~/.gradle folder

[1] https://gist.github.com/secondsun/7dd2b99a0047eb514a6d

**Comment by lholmquist** [comment]
i noticed that this is missed spelled,  https://github.com/secondsun/aerogear-android-cookbook/blob/fb0ac26c53a366ff0a514f0e3e46ca17ee10cb04/AuthExamples/app/src/main/java/org/jboss/aerogear/android/cookbook/authexamples/HowToUseDigestAuthentication.java#L50

not sure if it really matters

**Comment by danielpassos** [comment]
@lholmquist All you notice, matter for us :)

**Comment by lholmquist** [comment]
on the GDrive example,  after i accept the "consent" screen,  the Dialog is still up it says to paste this code in your app.   

i'd send a screen shot but not sure how to do that on my galaxy s4

**Comment by secondsun** [comment]
Hold power and volume down to take a screenshot.  This is PROBABLY a
problem in the setup of the demo and not a fault of code.  IE we need to
update the README.

Could you check and make sure you followed the directions exactly?

Summers Pittman
>>Phone:404 941 4698
>>Java is my crack.

**Comment by secondsun** [comment]
Closed in favor of https://github.com/aerogear/aerogear-android-cookbook/pull/39

**Pull request closed without merging**
