### PR TITLE
Update Hellopush to Android N

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by danielpassos** [comment]
@secondsun  👀 ?

**Comment by danielpassos** [comment]
@secondsun  👀 ?

**Comment by aidenkeating** [comment]
Taking a look :)

**Comment by aidenkeating** [comment]
@danielpassos Verified! Added some lovely screenshots below.

[No notifications](https://cloud.githubusercontent.com/assets/8698527/20215529/be49b794-a80c-11e6-8a3d-4dde445be65e.png)

[UPS Console](https://cloud.githubusercontent.com/assets/8698527/20215531/be531a00-a80c-11e6-8596-726bc83ee3ca.png)

[New notification!](https://cloud.githubusercontent.com/assets/8698527/20215530/be4ee282-a80c-11e6-8f3c-3397a77dded9.png)

**Comment by danielpassos** [comment]
@aidenkeating

**Pull request merged**
