### PR TITLE
Update gradle instruction

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by danielpassos** [comment]
@aidenkeating @jcesarmobile Quickly sanity review?

**Comment by aidenkeating** [comment]
@danielpassos Is this just updating READMEs for the tasks that are already completed? If so, should `CarStore` be updated too?

**Comment by danielpassos** [comment]
@aidenkeating Yes, that is the idea. I have added the `CarStore` in the another PR. See https://github.com/aerogear/aerogear-android-cookbook/pull/62

**Comment by aidenkeating** [comment]
@danielpassos Aha! Then this looks awesome! 👍

**Comment by jcesarmobile** [comment]
LGTM

**Comment by danielpassos** [comment]
Landed at https://github.com/aerogear/aerogear-android-cookbook/commit/ca15da4f2895601ea904a45f89ed7744fbb5422d

**Pull request closed without merging**
